spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update                        # 스키마 자동 생성 옵션
    database-platform: org.hibernate.dialect.OracleDialect  # Hibernate Dialect 설정
    properties:
      hibernate:
        show_sql: true                        # SQL 쿼리를 콘솔에 출력
        format_sql: true                      # SQL 포맷팅 출력
        use_sql_comments: true               # SQL 주석 사용

  data:
    redis:
      host: localhost                         # Redis 서버 호스트
      port: 6379                              # Redis 기본 포트
      password: ""                            # Redis 비밀번호 (없다면 빈 값)

logging:
  level:
    org:
      hibernate:
        SQL: debug                            # Hibernate SQL 로그 레벨 설정
    com:
      your_project_package: debug             # 프로젝트 패키지에 대한 로그 레벨 설정
